# Generated by Django 4.1 on 2025-04-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        # Removed unsupported AlterField operations for djongo compatibility
    ]
